language: node_js
node_js:
  - "10"
  - "9"
  - "8"
  - "7"
  - "6"
sudo: enabled
script:
  - npm test
  - npm run lint
notifications:
  email:
    recipients:
      - qwhexz@gmail.com
      - balazs.saros@gmail.com
    on_success: never
    on_failure: always
